### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by eknkc** [aheckmann/gm#104]
Is there any way to specify a timeout duration for GM operations? AFAIK Node supports that natively in child process module.

Thing is, I perform on demand image resizing with GM, sometimes, people upload 20MB GIF files, or highly compressed small / high resolution files. GM uses a lot of resources while working on them. I'd like to have an option to say "if this takes more than a second, just kill it and return an error".

**Comment by marcbachmann** [comment]
Maybe a bit late for you, but here's a pull-request that adds timeout support: #382

**Comment by rwky** [comment]
@marcbachmann Excellent, at a quick glance it looks good I'll check it out this week and merge.

**Comment by marcbachmann** [comment]
Great. Thanks.
