### ISSUE TITLE
How to create a thumbnail and preserve aspect ratio?

### ISSUE THREAD

**Issue by rabbitfufu** [aheckmann/gm#179]
I am using the following code to render a thumbnail:

<pre>
gm( origPath ).thumb( 100, 0, cachePath, 95, cb );
</pre>

This seems to work however it also returns the following error to the callback:

<pre>
{ [Error: Command failed: gm convert: geometry dimensions are zero (unable to crop image).
] code: 1, signal: null }
</pre>

What is the proper way to create a thumbnail of an image and have it maintain the correct aspect ratio? (When you only have the width of the image)

**Comment by FlandersBurger** [comment]
I'm also running into this. what parameters should be passed to gm to avoid this?
