### ISSUE TITLE
IPTC data in identify

### ISSUE THREAD

**Issue by dmmalam** [aheckmann/gm#20]
Hey,

graphicsmagik returns IPTC data such as caption, GPS etc on the command line

> gm identify -ping -verbose image.jpg

However the node gm identify wrapper only returns a subset of this data, even thought it uses the same command as above.

I believe only few changes will be needed to the parser that transforms stdout to JSON.

**Comment by rhyslbw** [comment]
I'm having the same problem with Profile-iptc

**Comment by rayshan** [comment]
@dmmalam @rhyslbw `Profile-iptc` only works when ImageMagick is used, as tested here: https://github.com/aheckmann/gm/blob/master/test/getterIptc.js#L18

Sample output:
```js
Profiles:
   { 'Profile-8bim': '10304 bytes',
     'Profile-exif': '10730 bytes',
     'Profile-icc': '3144 bytes',
     'Profile-iptc':
      { 'City[1,90]': '0x00000000: 254700                                        -%',
        'Image Name[2,5]': 'Test Title.',
        'Keyword[2,25]': 'ray shan',
        'Created Date[2,55]': '20120831',
        'Created Time[2,60]': '184714',
        'unknown[2,62]': '20120831',
        'unknown[2,63]': '184714',
        'Byline[2,80]': 'Creator Ray Shan',
        'City[2,90]': 'Minneapolis',
        'Sub-Location[2,92]': 'Calhoun Isles',
        'Province State[2,95]': 'Minnesota',
        'Country Code[2,100]': 'US',
        'Country[2,101]': 'United States',
        'Headline[2,105]': 'IPTC Headline',
        'Copyright String[2,116]': 'Copyright all rights reserved',
        'Caption[2,120]': 'Test Caption.' },
     'Profile-xmp': '4617 bytes' },
```

@aheckmann not sure if GraphicsMagick didn't output this in 2012, but it does now. Perhaps don't require ImageMagick now?

**Comment by rhyslbw** [comment]
Thanks @rayshan . Yes this would be great to see available for gm too @aheckmann
