### ISSUE TITLE
pipe to gm

### ISSUE THREAD

**Issue by nickpoorman** [aheckmann/gm#233]
This is just a suggestion but it would be nice if you could pipe into gm.

``` js
request(url)
  .pipe(gm('img.jpg').createWriteStream())
  .pipe(gfs.createWriteStream({
     filename: 'img.jpg'
  }));
```

I know you can just pass in the `Buffer` from `request` but I was hoping there might be a way to pipe it directly in.

**Comment by winduptoy** [comment]
@jonathanong What happened to gm2? Did it get merged here? I too would like the ability to pipe to `gm`.
