### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by wthit56** [aheckmann/gm#241]
I have installed GraphicsMagick (I'm using Windows 7, and didn't want to build my own ImageMagick). In the folder with the source .js file being run is an image, _image.jpg_. I am using the following code:

``` js
var gm = require("gm");

gm("image.jpg")
    .size(function (error, size) {
        if (error) { throw error; }
        console.log(size);
    });
```

When I run it, I get the following error:

```
Error: spawn ENOENT
  at errnoException (child_process.js:980:11)
  at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Would really appreciate some help on this.

**Comment by syuilo** [comment]
I also had the same problem, but was solved by using the **cmd (administrator)** instead of **PowerShell**.

**Comment by jasonhargrove** [comment]
In PowerShell `gm` is in use and one must use `gm.exe`

![image](https://user-images.githubusercontent.com/285708/92292327-9eab3600-eeea-11ea-9e3c-5ce324a08d78.png)

Looks like I can pass an `appPath` arg, but gm is a dependency of a module I'm testing. Will look into what kind of fix is best.

In the meantime this is the only issue that contains `powershell` so I've added this note in case anyone should need it
