### ISSUE TITLE
question: how to use +adjoin ?

### ISSUE THREAD

**Issue by smartcris** [aheckmann/gm#261]
GraphicsMagick 1.3.15, added new requirement to use adjoin for spliting one multipage image in numbered output files. I need some help to convert in node.js gm  the following instructions:

gm convert +adjoin -trim input.pdf PNG8:output%03d.png

Thank you!

**Comment by tnbeatty** [comment]
@v4l3r10 Did you ever figure out how to use +adjoin with a buffer output?

**Comment by v4l3r10** [comment]
@tnbeatty  switched to node-pdfutils  bro! but last update is very old ;)

this is my old code
```javascript
pdfutils(bufferPDF, function(err, buffer) { 
 //buffer as an array of buffer for every page
    for (i = 0; i < buffer.len && !stop; i++) {
      var imageStream = buffer[i].asPNG({
        maxWidth: 1200,
        minWidth: 1000
      })
      imageStream.pipe(....);
    }
...
});
```

I hope it can be useful

**Comment by Veejay** [comment]
@smartcris : 

```
gm convert +adjoin -trim input.pdf PNG8:output%03d.png
```

Is there a way to cut a single page image into tiles of X by Y and use that as "pages" in the same way? I'd love to be able to cut tiles from an image and have them be saved to sequentially numbered output files.

**Comment by Veejay** [comment]
OK, found a way, I'll leave that here for the next person :

To cut a `1024x3072` image into (48 I guess) sequentially numbered `256x256` TIFF files (`tile-000.tiff`, `tile-001.tiff`, etc):

```javascript
const gm = require('gm')

gm(PATH_TO_IMAGE_FILE)
.command('convert')
.out('-crop')
.out('256x256')
.out('+adjoin')
.out('-trim')
.write('tile-%03d.tiff', (error) => {
  if (error) {
    console.error(error)
  }
})
```

which maps to the following `GraphickMagick` command:

```
gm convert -crop 256x256 PATH_TO_IMAGE_FILE +adjoin -trim tile-%03d.tiff
```

#### Note

* Using `.crop(256,256)` instead of `.out('-crop').out('256x256')` has a different behaviour and only yields a single `256x256` tile. Not sure why.

**Comment by jraut** [comment]
Could using adjoin return an array of buffers instead of a single buffer?

**Comment by nsitu** [comment]
I am using `ImageMagick` via `gm` so I'm not sure if this applies here, but I wanted to share an approach that allowed me to create an array of images. In ImageMagick you can output to base64 using `inline`. See also: [https://imagemagick.org/Usage/files/#inline](https://imagemagick.org/Usage/files/#inline). As noted in the documentation, ImageMagick prefixes each inline image with something like `data:image/png;base64,`. (Notice the comma at the end). 
  
Applying this in the context of `.toBuffer()` one may split the string into an array, using the prefix as a delimiter. You may need to do further work if base64 doesn't work for you, but at least you would have a workable array. You might be able to build a variation on this to meet your needs.
  
```javascript  
.toBuffer('inline:png',function(err,buffer){   
    /* ... handle errors here ... */  
  
    // split string into array
    const images = buffer.toString().split('data:image/png;base64,') 
   // remove the first element since it will be blank  
    images.shift()     
  
    /* ...images array is now populated with base64 encoded PNGs... */
}) 
```
