### ISSUE TITLE
Looks like Imagemagick doesn't work on Windows

### ISSUE THREAD

**Issue by fetis** [aheckmann/gm#264]
Hello.

I installed Imagemagick but can't make it work with gm module. It works fine from command line, but still inaccessible from node.js

Graphicsmagic btw works fine right out the box

One more note. I tried "node-imagemagick" module and it works fine, so it looks like problem in gm somewhere

**Comment by jimior2** [comment]
didn't work on ImageMagick-6.9.3-8-Q16-x64-dll.exe, dese this work on specific version of ImageMagick?

**Comment by jjhesk** [comment]
this is `GraphicsMagick-1.3.24-Q16` and it is not working

**Comment by amilajack** [comment]
Is there a way to install ImageMagick or GraphicsMagick on appveyor?
