### ISSUE TITLE
Support for PSD files?

### ISSUE THREAD

**Issue by jpadilla** [aheckmann/gm#265]
Does gm support converting PSD files to PNG? This definitely works using convert.

**Comment by meteormatt** [comment]
https://github.com/aheckmann/gm/blob/master/examples/flatten.js
There is example, I think.

**Comment by hutaoer** [comment]
The gm has some bugs in converting PSD to PNG。Such as some psd with big size can not be converted well to png file. The produced png file loses some parts of elements in orginal PSD file.

**Comment by meteormatt** [comment]
I found [PSD.js](http://meltingice.github.io/psd.js/) now. Seems have better performance than `ImageMagick` or `GraphicsMagick`.
