### ISSUE TITLE
Error: spawn ENOMEM

### ISSUE THREAD

**Issue by cloudgifts** [aheckmann/gm#292]
Randomly, I get the following error.  I say randomly, because sometimes my image is generated just fine and other times I get the error (even for the same image).  It is repeatable, just not all the time.

Error: spawn ENOMEM at errnoException (child_process.js:980:11) at ChildProcess.spawn (child_process.js:927:11) at exports.spawn (child_process.js:715:9) at gm._spawn (/home/node/cloudcash-server/app/node_modules/gm/lib/command.js:187:16) at /home/node/cloudcash-server/app/node_modules/gm/lib/command.js:117:19 at series (/home/node/cloudcash-server/app/node_modules/gm/node_modules/array-series/index.js:11:36) at gm._preprocess (/home/node/cloudcash-server/app/node_modules/gm/lib/command.js:154:5) at gm.stream (/home/node/cloudcash-server/app/node_modules/gm/lib/command.js:115:10) at gm.toBuffer (/home/node/cloudcash-server/app/node_modules/gm/lib/command.js:139:17) at createImageBuffer (/home/node/cloudcash-server/app/app_modules/utilities-----logo-custom-sizer.js:125:18)

**Comment by throrin19** [comment]
I have the same problem with a server with 17Go of RAM. If i ran many images in async each or eachLimit, i have ENOMEM randomly
