### ISSUE TITLE
PSD layer 0

### ISSUE THREAD

**Issue by johnlouis-swaine-axomic** [aheckmann/gm#298]
PSDs typically include layer 0 which is full a flattened composite.

Running imagemagick with the `-flatten` command doesn't always produce the right outcome so I've been patching a bit under the gif layer check code 

```
  if (typeof source === "string") {
    // then source is a path

    // parse out gif frame brackets from filename
    // since stream doesn't use source path
    // eg. "filename.gif[0]"
    var frames = source.match(/(\[.+\])$/);
    if (frames) {
      this.sourceFrames = source.substr(frames.index, frames[0].length);
      source = source.substr(0, frames.index);
    } else {
       /// Alteration
      if (source.match(/.[Pp][Ss][Dd]$/)) this.sourceFrames = "[0]";                                 
    }
}
  this.source = source;

  this.addSrcFormatter(function (src) {
    // must be first source formatter

    var inputFromStdin = this.sourceStream || this.sourceBuffer;
    var ret = inputFromStdin ? '-' : this.source;

    if (ret && this.sourceFrames) ret += this.sourceFrames;

    src.length = 0;
    src[0] = ret;
  });
}
```

Anyone know of a nicer way to append the `[0]` layer selector to the input?  Particularly when dealing with a stream/buffer input? eg: `-[0]`?

I'd have added it using the typical .arg() formatting and submitted it as a Pull Request if it didn't need to alter the input argument. This way works but I'm conscious of the fact that it's not especially nice.

Any suggestions would be very much appreciated :)

**Comment by knlykos** [comment]
Hi you can try this, it is working for me

`    gm(req.file.path)
      .command("convert")
      .out(`${filePath}[0]`)
      .write("path", (err) => {
        if (err) {
          console.log(err);
        }
        console.log("ok");
      });`
