### ISSUE TITLE
OSX 10.10 compatibility

### ISSUE THREAD

**Issue by jgainfort** [aheckmann/gm#348]
Some colleagues of mine running Windows 8 and OS X 10.9.5 are running gm without any issues. I on the other hand with OS X 10.10.1 seem to run into some errors.

Could anyone confirm that they are using gm with imagemagick successfully on 10.10?

**Comment by viki53** [comment]
Hi,

I've used it every day for about a week ½ now on Yosemite without any issue.

I'm only using basic options for now (resize, read size, stream, write…), maybe you're using advanced options?

**Comment by jgainfort** [comment]
I forgot I posted here otherwise I would have mentioned I found the problem. It turned out that my brew install of imagemagick wasn't linking to libpng properly. I had to find an alternative install to fix my issue. However after I did a reformat and retried the brew install everything worked perfectly. Maybe it was just a bug that occurred during the upgrade from 10.9.5 to 10.10.1.
