### ISSUE TITLE
Weird Error while retrieve the first frame of the picture ( gif or pdf )

### ISSUE THREAD

**Issue by benpptung** [aheckmann/gm#350]
Hi I keep to get the following weird error while trying to retrieve the first frame of the picture( animated gif or multiple pages pdf).
The code is looking like the following:

```
var im = require('gm').subClass({imageMagick: true}),
    resolve = require('path').resolve,
    fs = require('fs');

im(fs.createReadStream(resolve(__dirname, 'path/to/', 'document.pdf')))
.in('[0]')
.write(resolve(__dirname, 'test.jpg'), function(err){
  if (err) console.log(err);
})
```

It works!! But I got the following error:

> { [Error: Command failed: convert: no decode delegate for this image format `/var/tmp/magick-1723873yKKCuYqqmv' @ error/constitute.c/ReadImage/552.
> ] code: 1, signal: null }

In addition, the more weird situation is, if I use .stream() instead of .write(), it will only work for gif format.
The code of using stream is looking like the following:

```
var im = require('gm').subClass({imageMagick: true}),
    resolve = require('path').resolve,
    fs = require('fs');

im(fs.createReadStream(resolve(__dirname, 'path/to/', 'document.pdf')))
.in('[0]')
.stream()
.pipe(fs.createWriteStream(resolve(__dirname, 'test.jpg')));
```

The above code works to retrieve the first frame of animated gif file, but not working for pdf.
I am sorry that I am using imagemagick, because GraphicMagick has an unknown bug to handle psd format file, and psd format is very important to our business. We draw online caricature :)

Thank you in advance if any help :)

**Comment by meteormatt** [comment]
I found the solution here.
#208

The code should be
```js
var im = require('gm').subClass({imageMagick: true}),
    resolve = require('path').resolve,
    fs = require('fs');
im(fs.createReadStream(resolve(__dirname, 'path/to/', 'document.pdf')))
.selectFrame(0)
.pipe(fs.createWriteStream(resolve(__dirname, 'test.jpg')));
```
