### ISSUE TITLE
write EPIPE error, but IM is installed

### ISSUE THREAD

**Issue by mega-cache-money** [aheckmann/gm#359]
I was using this module happily for months in my app. Today it started throwing:

    events.js:72
            throw er; // Unhandled 'error' event
              ^
    Error: write EPIPE
        at errnoException (net.js:904:11)
        at Object.afterWrite (net.js:720:19)

I am pretty certain I haven't changed anything relating to `gm`, which is why this is super weird. The fact that it's such a vague error message doesn't exactly help. I've specified an error-handling callback in the one place I use `gm`, which isn't called with an error here. If I comment it out, everything works (this took ages to figure out), so it must be this that's causing the issue. 

Since what I'm trying to do is to resize an image, I've run `convert ... -resize` via the command line, to test imagemagick itself, with no error. 

What is likely to be going on here?
Any ideas for troubleshooting?

FWIW here's my little `gm` snippet that's erroring:

    function createThumbnail(imageBuffer, callback) {
      gm(imageBuffer)
      .options({imageMagick : true})
      .resize(120,127)
      .toBuffer('JPG', callback);
    }

I'm certain `imageBuffer` contains a valid image.

**Comment by agross** [comment]
:+1: Seems like `this._options.appPath` is undefinded in command.js:214. This is actually the only reference to `_options.appPath` I could find.

**Comment by mega-cache-money** [comment]
@agross Thanks for investigating! Why would this `this._options.appPath` spontaneously become undefined? What does it being undefined imply? How would one go about resolving this?

**Comment by agross** [comment]
@mega-cache-money I don't know either. I just took some time to inspect. I use gm with `gulp-image-resize` which requires ´gulp-gm` which in turn requires `gm`. Neither of first two have `appPath` in their source files.

Perhaps @aheckmann knows more?

**Comment by mega-cache-money** [comment]
I reinstalled both imagemagick and graphicsmagick, restarted, and it's
working!

**Comment by rwky** [comment]
If a reinstall fixed it then it sounds like for some reason the module couldn't find your gm/convert binary, the error is cryptic and should be patched I think we have a PR for it I'll see if I can find it and merge it :)

**Comment by piotr-cz** [comment]
Computer restart after ImageMagick installation and no issue for me.
BTW looks like it's a duplicate of #209

**Comment by briandonahue** [comment]
This is a strange issue, I am having as well.  I can't reboot the machine as it is a remote/active server.  I don't understand why that would be necessary, I have checked and my `$PATH` is correct with IM and GM visible.  I can run IM directly by setting `convert.path= "C:\\Program Files\\ImageMagick-7.0.1-Q16\\magick.exe"` but doing so in GM with:
`require('gm').subClass({ imageMagick: true, appPath:  "C:\\Program Files\\ImageMagick-7.0.1-Q16\\magick.exe"})` still gives me the `EPIPE` error.  😕
