### ISSUE TITLE
Fails on strict mode

### ISSUE THREAD

**Issue by tresdin** [aheckmann/gm#362]
Whenever I run my app on strict mode, node throws the error `Use of const in strict mode` in `node_modules/gm/lib/getters.js:13`. What should I do with this bug?

**Comment by tjconcept** [comment]
Do not run your app in strict mode.

You're literally saying to node "run my code, and everyone else's code with other semantics than it was written for". It is kind of like running ruby code in node. "Strict mode" just happens to be close enough to actually work in 80% of the cases.

"Strict mode" is more than just added warnings, it is other semantics.

**Comment by davemackintosh** [comment]
@tresdin use the `"use strict";` pragma instead of the `--use_strict` flag.
