### ISSUE TITLE
gm.write BUG

### ISSUE THREAD

**Issue by bl0zis** [aheckmann/gm#372]
For example, when I try to write file with name:

 - Sem T**í**tulo.png
 - **É** Sem Titulo.png

The result is:

 - Sem Titulo.png
 - E Sem Titulo.png

And when i try to check if file exist, the result is always false x)

**Comment by rwky** [comment]
Works fine for me, gm.write spawns the gm binary and uses that to write the file so it'll be something to do with your system not the module.
