### ISSUE TITLE
Execute custom imagemagick command

### ISSUE THREAD

**Issue by klimashkin** [aheckmann/gm#389]
Sorry, I did'n quiet understand by docs how to execute imagemagick command with callback?
For example this:
```convert beh83jzjzy8dugo36y.jpg -quality 100 -gravity South -background #888 -splice 0x21.84 -gravity southwest -font AdobeFanHeitiStd-Bold.otf -pointsize 14.56 -stroke none -fill #e8e8e8 -annotate +36+7  helloworld  1.2133333333333334  14.56  21.84 \( logo.png -quality 100 -resize 50% \) -composite out.jpg```

**Comment by rwky** [comment]
You need to use the `.in` and `.out` methods to pass your custom options documented here https://github.com/aheckmann/gm#custom-arguments
