### ISSUE TITLE
GraphicsMagick or Imagemagick support is requirement

### ISSUE THREAD

**Issue by black-perl** [aheckmann/gm#390]
Hey,

I am on Ubuntu 14.04 and is trying to use the node `gm` package. I installed the `GraphicsMagick` correctly and is able to run the `gm` from command line on my system. But I am unable to use the `node-gm` package in REPL getting the traditional error : 

    >  { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

Then, I went on to install `Imagemagick` and everything started working ! 

So, I want to know whether both of them are required for the module to work ? If not, how can I get it working with 'gm'.

**Comment by rwky** [comment]
No only one is required, it could be gm is installed outside your environment's PATH, you can also used the appPath option to specify where to look for gm.

**Comment by black-perl** [comment]
Sure, thanks !
