### ISSUE TITLE
ReferenceError: extension is not defined

### ISSUE THREAD

**Issue by bhaveshvavdiya** [aheckmann/gm#391]
Hey all,

I am using ImageMagick with nodejs and trying to run below code.								
gm(myfiles[0].fd)
    .quality(65)
    .resize(960,1280,'>')
    .write('assets/thumbnail/gm.jpg', function (err) {
        console.log(err);
    });
It gives me error "ReferenceError: extension is not defined".
I also set the all environment variable. I dont know why this error comes.
Please Help me.

Thanks

**Comment by rwky** [comment]
That's a problem with your code, somewhere you've tried using the variable extension but not defined it previously.
