### ISSUE TITLE
https links are not supported

### ISSUE THREAD

**Issue by elbajo** [aheckmann/gm#398]
https links don't seem to be supported, it would be great to have this working.

Example:
```
gm('https://www.eff.org/files/https-everywhere2.jpg')
    .size(function(err, size) {
                if (!err)
                    console.log(size.width > size.height ? 'wider' : 'taller than you');
                else
                    console.log(err);
        });
```

**Comment by rwky** [comment]
That's a limit of gm not of the module. gm doesn't support https (and in fact I can't spot anything saying it supports http but it does).
