### ISSUE TITLE
Failing to create composite images

### ISSUE THREAD

**Issue by agnivade** [aheckmann/gm#400]
Hello,

I am using this code, to create a composite image - 

```
gm()
.in('-page', '+0+0')
.in('./img1')
.in('-page', '+1280+0')
.in('./img2')
.mosaic()
.write('./finalimg', function(err) {
  if (err) {
  console.error('Error in writing the image- {}'.format(err));
  return;
 }
 debug('wrote image');
});
```

I have 2 1280x720 images.

However, at the end, I am getting a binary file. And I can't open that.

Can someone point out to what I am doing wrong ?

The raw command - 
```
gm convert -page +0+0 ./img1 -page +1280+0 ./img2 -mosaic ./finalimg
```
works.

**Comment by agnivade** [comment]
I found out the issue. It works only when I give a file extension to the output file. But the raw command still works without the extension. Any reason ?

**Comment by rwky** [comment]
The extension tells gm what format to save the image in, not specifying a format can have unforeseen consequences (as you've found out!)
