### ISSUE TITLE
It work well before. But now, I got this error in mac.

### ISSUE THREAD

**Issue by Naixor** [aheckmann/gm#404]
```JavaScript
{ [Error: spawn convert ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn convert',
  path: 'convert' }
```

**Comment by rwky** [comment]
Looks like you don't have imagemagick installed.

**Comment by Naixor** [comment]
I m sure that I have installed, it works yesterday... I will check soon.

**Comment by Naixor** [comment]
Warning: imagemagick-6.9.0-10 already installed

**Comment by rwky** [comment]
ENOENT means it can't find it, it could be missing from your PATH try setting appPath in the gm options to where imagemagick is installed (not including the binary) so if it's in /usr/local/bin you'd use `options = { appPath: '/usr/local/bin/' }`

**Comment by Naixor** [comment]
Thank you~
