### ISSUE TITLE
Version of GraphicsMagick

### ISSUE THREAD

**Issue by achingbrain** [aheckmann/gm#406]
Is there any way to find out what version of GraphicsMagick this module is using in the background?

**Comment by rwky** [comment]
Whatever version you have installed it doesn't come bundled with one. Use `gm -version`

**Comment by achingbrain** [comment]
No, I mean can I find the gm version from the module itself?

**Comment by rwky** [comment]
You could use the `.in` option to pass -version then parse the output.

**Comment by achingbrain** [comment]
Clunky, but it works. Thanks.
