### ISSUE TITLE
Resize PNG to smaller dimensions creates larger size file 

### ISSUE THREAD

**Issue by noam3127** [aheckmann/gm#411]
It apparently only happens with this specific image:
![io](https://cloud.githubusercontent.com/assets/5139052/8116286/3815f3be-104f-11e5-8caa-19b4fdcc25cb.png)
The original image file is 11.4 kb and its dimensions are 1369 X 1563. After doing `gm(buffer).resize(550, null)`  the resized image has a much larger file size - 26.6 kb, but it has the correct dimensions of 550 X 628.

**Comment by rwky** [comment]
The source image has probably been put through a compressor, gm/convert aren't brilliant at doing this. I find compressing with pngquant https://pngquant.org/ improves png file size greatly
