### ISSUE TITLE
Enoent with spawn but not exec

### ISSUE THREAD

**Issue by camj256** [aheckmann/gm#412]
So I've spent almost 12 hours on this today and I probably should've started here.

I'm seeing:
[Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%m" "-" this most likely means the gm/convert binaries can't be found]

Path seems set up correctly:
[root@Node your-daily-trends]$ which convert
/usr/bin/convert
[root@Node your-daily-trends]$ which identify
/usr/bin/identify
[root@Node your-daily-trends]$ which gm
/usr/local/bin/gm
[root@Node your-daily-trends]$ echo $PATH
/home/cam/.linuxbrew/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/cam/npm/bin:/home/cam/bin:/home/cam/npm/bin
[root@Node your-daily-trends]$ node --version
v0.12.4
[root@Node your-daily-trends]$ npm --version
2.10.1

I'm on Centos 6.6

When I run:
```javascript
       var spawn = require("child_process").spawn,
      child  = spawn("gm", ["version"']);

        child.stdout.on('data', function (data) {console.log(data.toString('utf-8'));});
        child.stderr.on('data', function (data) {console.log(data.toString('utf-8'));});
```

I see enoent error.

When I do:
```javascript
        var exec = require('child_process').exec;

        exec("gm -version", function (error, stdout, stderr) {
            if (error) console.log(error);
            console.log(stdout);
            console.log(stderr);
        });
```

It works fine.

I've checked and node is seeing the same path variables. I can access imagemagick/graphicsmagick fine from terminal.

ImageMagick is installed via Yum. GraphicsMagick is the newest version and installed via make install.

I've also removed both at one point and tried using linuxbrew. No luck there. I'm baffled as to whats going on here.

**Comment by camj256** [comment]
Sometimes you just need to sit down and write out a problem to realize you are doing something stupid.

I was checking the node path stuff in node but only on the first process. My app forks a different process for each core of the CPU. (cluster sucks with socket.io!)

Anyway, I just had to pass it process.env.PATH and it works now.

**Comment by lmj0011** [comment]
I know this answer is old, but you really could have elaborated more on what you passed `process.env.PATH` to.
