### ISSUE TITLE
ERROR: spawn EMFILE (80 file limit?)

### ISSUE THREAD

**Issue by dennishall** [aheckmann/gm#42]
Error: spawn EMFILE
    at errnoException (child_process.js:481:11)
    at ChildProcess.spawn (child_process.js:444:11)
    at child_process.js:342:9
    at gm._spawn (/Users/myusername/node_modules/gm/lib/command.js:156:16)
    at gm._exec (/Users/myusername/node_modules/gm/lib/command.js:137:17)
    at gm.identify (/Users/myusername/node_modules/gm/lib/getters.js:74:10)
    at gm.size (/Users/myusername/node_modules/gm/lib/getters.js:33:12)

.. attempted **to walk a directory**, getting image sizes for each image encountered.

Node: 0.6.12
OS: mac osx 10.6.8

I tried directly `calling gm(<filename>).size(function(e, v){ ... });` on the last file in the list before the error, and it worked fine.

I created an array literal containing the 81 image filenames logged to the console leading up to the error and iterating over just them. Same result. But as soon as I removed _any one_ of them from the array, everything was ok.

**Comment by lucaswxp** [comment]
I'm still experiencing this issue. How to I close the gm opened file descriptor manually?

Here is my code:

```javascript
var series = [];
          for(var i in files){ var file = files[i];
            (function(file){
              series.push(function(resolve){
                  gm(file)
                    .resize(null, 200)
                    .quality(80)
                    .write(file, function (err) {
                      if (err) console.log(err);

                      resolve();
                    });
                });
            })(file);

            async.series(series);
```

**Comment by barbasa** [comment]
@cyrus-za  can you give us an example of code on how you did it ? I'm having the same issue but I haven't managed to fix it :/

Thanks!

**Comment by jSchapiroAtTheMelt** [comment]
I think the point is to simulate the calls to gm "synchronously" where as the normal calls are async and spawn a new process each time.

**Comment by jSchapiroAtTheMelt** [comment]
@dennishall thank you so much for this. worked like a charm! was going to do everything synchronously with callbacks but this is much better!
