### ISSUE TITLE
Hex colour values need to be wrapped

### ISSUE THREAD

**Issue by andrey-p** [aheckmann/gm#422]
Passing a hex value as an option to `compare`:

```
gm.compare("foo.png", "bar.png", { highlightColor: "#fff", file: "baz.png" }, function () { ... });
```

Leads to this error:

```
gm compare: Option '-highlight-color' requires an argument or argument is malformed.
```

Wrapping the value manually makes things work:

```
gm.compare("foo.png", "bar.png", { highlightColor: "\"#fff\"", file: "baz.png" }, function () { ... });
```

Having to wrap a hex value manually seems counterintuitive. Do you think this is something `gm` should do automatically?

**Comment by rwky** [comment]
Yep makes sense gm should do that for you.
