### ISSUE TITLE
Format inference with buffers and streams

### ISSUE THREAD

**Issue by adurrive** [aheckmann/gm#429]
There is no format inference from the filename for input buffers or streams. Format inference from the file signature doesn't work with some formats like ico:

``` javascript
gm('/path/to/img.ico').size(function (err, size) { ...  });
```

> { width: 64, height: 64 }

``` javascript
buffer = fs.readFileSync('/path/to/img.ico');
gm(buffer, 'img.ico').size(function (err, size) { ...  }); 

stream = fs.createReadStream('/path/to/img.ico');
gm(stream, 'img.ico').size({bufferStream: true}, function (err, size) { ...  }); 
```

> { [Error: Command failed: gm identify: No decode delegate for this image format (/tmp/gm3mwq).
> gm identify: Request did not return an image.
> ] code: 1, signal: null }

**Comment by adurrive** [comment]
Fixed by https://github.com/aheckmann/gm/pull/430

**Comment by freund17** [comment]
There is no format inference from the filename for input buffers or streams. 

I created a PR for that: https://github.com/aheckmann/gm/pull/701
