### ISSUE TITLE
Please publish to npm.

### ISSUE THREAD

**Issue by Maksims** [aheckmann/gm#443]
Latest version has serious fix for streams: #430 that is holding us a bit back for automated deployment to production, using npm.
NPM has older version from May, and its September already :)

Please publish latest version to NPM.

**Comment by rwky** [comment]
I'll go through things Wed/Thurs and publish one of those days.

**Comment by Maksims** [comment]
Thank you.
Just to mention, we could install from tarball, but tag 1.18.1 actually is old, and does not includes fix #430 which was merged later.
If at least you make another release version tag, it will help to install from tarball for now.

**Comment by rwky** [comment]
Done! New tag and new npm version.
