### ISSUE TITLE
The gm/convert binaries can't be found

### ISSUE THREAD

**Issue by osotorrio** [aheckmann/gm#455]
I am running Nodejs v4.1.1 in Windows 10 (64-bit). When I execute the following code:

var gm = require('gm').subClass({imageMagick: true});

gm('C:/Images/myImage.png').identify(function (err, data) {
      if (err) { 
              console.log(err); 
      }else{
              console.log(data); 
}});

I get the next error message:

gm {
  domain:
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events: { identify: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _options: { imageMagick: true },
  data: {},
  _in: [],
  _out: [],
  _outputFormat: null,
  _subCommand: 'convert',
  source: 'C:/Images/myImage.png',
  _sourceFormatters: [ [Function] ],
  _identifyState: 1,
  bufferStream: false }

[Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-verbose" "C:/Images/myImage.png" this most likely means the gm/convert binaries can't be found]

**Comment by jeonghwan-kim** [comment]
+1

**Comment by donghanji** [comment]
+1

**Comment by donghanji** [comment]
First,should install GraphicsMagic,in Mac:

> brew install GraphicsMagick

if install graphicsmagick by this way,you should config PATH:

Second,vim bash_profile,to export graphicsmagick path:

> vim ~/.bash_profile

add this code in bash_profile:

> export PATH=${PATH}:/usr/local/Cellar/graphicsmagick/1.3.21/bin

(notice:this is my graphicsmagick path,chang it as yours)

Third,reboot your term,and restart your server.

good luck ^_^

**Comment by jeonghwan-kim** [comment]
In my case, reinstall homebrew and install graphicsMagic again.

**Comment by moranm6** [comment]
+1 on windows. Tried restarting and installing with `npm install -g gm`

**Comment by donghanji** [comment]
moranm6 ,I think you shouldn't install graphicsMagic or ImageMagick,not a npm module,which are Stand-alone programs.

see here:
about graphicsmagick:http://www.graphicsmagick.org/index.html
about gm:https://github.com/aheckmann/gm

good luck ^_^

**Comment by kenberkeley** [comment]
If I were you, I would try this:
    sudo ln -s /usr/local/bin/gm /usr/bin/gm
    sudo ln -s /usr/local/bin/convert /usr/bin/convert

**Comment by jonas-db** [comment]
How do i fix this? i'm on windows 8.1 and i've installed this link: ImageMagick-6.9.2-5-Q16-x64-dll.exe

Please help!

**Comment by kmsheng** [comment]
+1 on mac

**Comment by rwky** [comment]
You need to install the binaries (convert/gm) and this module. The binary install will depend on your OS and you should check their respective documentation.

**Comment by leegee** [comment]
Should I open a new ticket for this?

I can find `convert` but it seems `gm` cannot.

```Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "/Users/lee/src/jsscroll/bin/../htdocs/img/passmore-fg.small.png" "-edge" "2" "-resize" "1000x" "[object Object]" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/gm/lib/command.js:299:14)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
14:57:05 $ which convert
/usr/local/bin/convert
14:59:27 $ convert --version
Version: ImageMagick 6.9.2-8 Q8 x86_64 2015-12-15 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib cairo fontconfig freetype gvc jng jpeg lcms ltdl lzma png rsvg tiff webp xml zlib
14:59:39 $
```

**Comment by devmetal** [comment]
@leegee  +1 here. Same problem in windows. The convert command working perfectly in the command line but if i try run this with node:

```JavaScript
function gmConvert(from, format, to) {
  return new Promise((resolve, reject) => {
    gm(from).setFormat(format).write(to, (err) => {
      if (err) return reject(err);
      resolve(to);
    });
  });
}

//Example parameters:
from -> D:\Programing\Nodejs\gmconv\testfile.NEF
to -> D:\Programing\Nodejs\gmconv\testfile.png
format -> png
```

I gave this error:
```
[Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "D:\Programing\Nodejs\gmconv\testfile.NEF" "png:D:\Programing\Nodejs\gmconv\testfile.png" this most likely means the gm/convert binaries can't be found]
```

But if i run this command:
```
convert testfile.NEF image.png
```

Its working perfectly

**Comment by devmetal** [comment]
-1 Sorry it was my fault. I found a solution. I installed imagemagick and i forgot about subClass:

```JavaScript
let imageMagick = gm.subClass({imageMagick: true});

imageMagick(...).write(...) //now working
```

Now its working perfectly

**Comment by leegee** [comment]
Exactly the same here — took me a long time to work that out: I 
reinstalled absolutely everything....!

Is it the docs or is it me?

**Comment by vanthome** [comment]
I also get this on Linux:

```
Error: Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
```

the `convert` command is installed and works however.

**Comment by ghigt** [comment]
same as @vanthome

**Comment by ktruckenmiller** [comment]
Tried @devmetal solution and it worked. 

I was running Alpine Linux in a docker container and I installed with
....
`RUN apk add --update imagemagick`
....

Then I just added this in my require within my node script:

`const gm = require('gm').subClass({imageMagick: true});`

**Comment by wahengchang** [comment]
same ubuntu, convert image.jpg new.jpg , works well. 

but not gm in node.js

**Comment by tomericco** [comment]
+1 on mac

**Comment by bluemix** [comment]
thanks to @ktruckenmiller, this worked with me (on Mac):
`const gm = require('gm').subClass({imageMagick: true});`

**Comment by phantomk** [comment]
think to @ktruckenmiller  , after installed ImageMagick on CentOS7, and subClass, it worked

**Comment by yunusde** [comment]
this works for me.

brew install imagemagick
brew install graphicsmagick

**Comment by mylonasg88** [comment]
On linux 
`Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "image.jpg" "-resize" "240x240" "/pdfOutput/res.jpg" this most likely means the gm/convert binaries can't be found`

Solution
`sudo apt install graphicsmagick`

**Comment by orangebook** [comment]
@mylonasg88  that is nice.
I Use Ubuntu 16.04 x64bit,and when I Man conver it ,there has two statment:
程序 'convert' 已包含在下列软件包中：
 * imagemagick
 * graphicsmagick-imagemagick-compat
请尝试：sudo apt install <选定的软件包>

then did this code in terminal:
 apt-get install  graphicsmagick-imagemagick-compat
that Ok

**Comment by shivashanmugam** [comment]
Windows solution
There is a scenario it worked when i renamed file  'magick.exe' to 'convert.exe' inside C:\Program Files\ImageMagick-<<Version No>> work.

**Comment by Shadow-Wizard** [comment]
For me it was bad node.js installation, as explained [here](http://stackoverflow.com/a/19661093/447356).

In short, you need to remove a trailing slash from node.js path.

**Comment by codeinaire** [comment]
Ubuntu 16.04. 
Using `image-to-ascii` in a javascript app. 
Error:
`[ Error: Stream yields empty buffer
....bunch of other stuff....
  Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
 .....bunch of other stuff..... ]`

Solution:
`sudo apt install graphicsmagick`

@mylonasg88 thanks!

**Comment by pj-alvarado10** [comment]
I love everybody! Thank you for your answers!

**Comment by aghiadyazji** [comment]
I had the same problem on Windows
make sure to check the option '_Install legacy utils_' as mentioned [here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/README.md#troubleshooting) when installing [ImageMagick](http://www.imagemagick.org/script/download.php)

**Comment by ziwer1** [comment]
If you are on windows, install GraphicsMagick instead of ImageMagick.
http://www.graphicsmagick.org/download.html

**Comment by katja-brunner** [comment]
Had the same issue on Windows 7 and solved it that way:

- install graphicsmagick from http://www.graphicsmagick.org/, not the node plugin
- install gm node plugin from https://github.com/aheckmann/gm
- add graphicsmagick installation folder and node js installation folder to your system path variable, e.g. C:\Program Files\GraphicsMagick-1.3.29-Q8;C:\Program Files\nodejs
- if you worked with cmd console, restart it to adopt system path variable changes! (that was my problem)

**Comment by Andrey7287** [comment]
Ok, now I can run gm on linux and windows , but how will it work on server ? I tried to run my app at heroku and have got same error :(

**Comment by xuya227939** [comment]
Hi, How do you work on Linux?

**Comment by Andrey7287** [comment]
Hi, just install graphicsmagic, see tip above.
https://github.com/aheckmann/gm/issues/455#issuecomment-255204399

**Comment by xuya227939** [comment]
是的，我照了上面安装了对应的graphicsmagick，还是提示这个错，我确定安装成功了。

**Comment by dominicfarraribm** [comment]
This works. takes 2 seconds. I tried everything on here and it didn't work. this worked. -> http://macappstore.org/imagemagick/

**Comment by zhubenjie** [comment]
windows
```javascript
 Error: Command failed: convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/714.

```

**Comment by damogallagher** [comment]
Hi

Is anyone aware of a nodejs library that will you to set a watermark on an image with installing imagemagick and graphicsmagick?
I want to be able to deploy a watermark service to AWS Lambda

**Comment by otanim** [comment]
for Ubuntu 16.04 LTS, according to @yunusde's solution, this works for me:
```bash
sudo apt-get install imagemagick
sudo apt-get install graphicsmagick
```

**Comment by JonathandelaSen** [comment]
I know this is so closed but I was having problems on Debian 9 with resizing images using "apt-get install graphicsmagick-imagemagick-compat" solution. "sudo apt-get install imagemagick" was the right solution for me.

**Comment by jackslocum** [comment]
After digging through the source, I found this solution for MacOS / Linux (will likely work on Windows too with appropriate path):

`let gm = require('gm').subClass({appPath: '/usr/local/bin/'});`

**Comment by 10001oleg** [comment]
> +1
> 
> also this issue:
> 
> [Error: Could not execute GraphicsMagick/ImageMagick: convert "a.png" "-resize" "300x300!" "b.png" this most likely means the gm/convert binaries can't be found]

same error

**Comment by xeroxstar** [comment]
I tried every solution were mentioned here and no success, if i run in console the **gm** command, works fine but if i run with the npm, i get same error **[Error: Could not execute GraphicsMagick/ImageMagick: convert "a.png" "-resize" "300x300!" "b.png" this most likely means the gm/convert binaries can't be found]**

**Comment by dotupNET** [comment]
> I tried every solution were mentioned here and no success, if i run in console the **gm** command, works fine but if i run with the npm, i get same error **[Error: Could not execute GraphicsMagick/ImageMagick: convert "a.png" "-resize" "300x300!" "b.png" this most likely means the gm/convert binaries can't be found]**
> 
> i installed on windows the GraphicsMagick-1.3.32-Q16 i restarted the pc, i installed npm install gm -g and here is my code:
> 
> ```
> 
> const gm = require('gm').subClass({addPath:'C://Program Files (x86)/GraphicsMagick-1.3.32-Q16'});
> gm('C://Users/user/Pictures/Chucks_0823.jpg').size(function (err, size) {
>         console.log(err)
> });
> ```
try this of course with your correc tpath:

const gm = require('gm').subClass({ imageMagick: true, appPath: path.normalize('C:**/**Program Files**/**ImageMagick-7.0.9-Q8**/**') });

**Comment by asotoglez** [comment]
It works for me
```
brew install imagemagick
brew install graphicsmagick
```

**Comment by g8up** [comment]
On windows , check this option when installing:
![image](https://user-images.githubusercontent.com/8005686/79015341-25a7ec80-7b9f-11ea-9abc-ad368820d304.png)

**Comment by msrumon** [comment]
Same problem here: `Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%m" "C:\Users\****\AppData\Local\Temp\ckc0sl1q40001iky9at0meiyz" this most likely means the gm/convert binaries can't be found`. I have installed GraphicsMagick on my Windows 10 by `choco install graphicsmagick`. Path also has been set w/ the installation process. I can access various commands exposed by `gm`, but I can't make it work on my Node.js project. Do I have to install 'ImageMagick' as well? I don't think so, **GraphicsMagick** is forked from _ImageMagick_ w/ lots of added benefits. This library doc also mentions to install one of them. Then why is it not working? Any idea?

**Comment by FullStackZz** [comment]
Windows platform:
1.download and install GraphicsMagick or ImageMagick windows version:
http://www.graphicsmagick.org/
http://www.imagemagick.org/
2.add to windows env path
CMD gm -version / convert -version
3.run node demo

**Comment by wsilva94** [comment]
Case use Docker with node:18 try this

**Comment by ramanabhinav7** [comment]
Could not execute GraphicsMagick/ImageMagick: '+cmd+" this most likely means the gm/convert binaries can't be found"
i have used npm install imagemagick and npm i gm but still this is showing in windows 
please help me 
const { fromPath } = require('pdf2pic');

const options = {
  density: 100,
  saveFilename: "untitled",
  savePath: "",
  format: "jpeg", 
  width: 600,
  height: 600
};

const convert = fromPath('invoice.pdf', options);
const pageToConvertAsImage = 1;

convert(pageToConvertAsImage, { responseType: "image" })
  .then((resolve) => {
    console.log("Page 1 is now converted as JPEG");

    return resolve;
  });
below is the error 
cb(new Error('Could not execute GraphicsMagick/ImageMagick: '+cmd+" this most likely means the gm/convert binaries can't be found"));
           ^

Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "-density" "100x100" "-quality" "75" "-[0]" "-resize" "600x600!" "-compress" "jpeg" "untitled.1.jpeg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\Users\ABHINAV KUMAR\Desktop\Node_jsm\innovice_jaishreemahakal\node_modules\gm\lib\command.js:249:12)
    at ChildProcess.emit (node:events:514:28)
    at cp.emit (C:\Users\ABHINAV KUMAR\Desktop\Node_jsm\innovice_jaishreemahakal\node_modules\cross-spawn\lib\enoent.js:36:37)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.9.0

**Comment by leonardocartaxo** [comment]
It worked for me in debian by adding these links

```
ln -s /usr/bin/gm /usr/local/bin/convert
ln -s /usr/bin/gm /usr/local/bin/magick
```
