### ISSUE TITLE
Error code meaning?

### ISSUE THREAD

**Issue by liuzhen2008** [aheckmann/gm#462]
I see that if I were to submit an image without proper encoding to gm("some_path").autoOrient().write("some_name", function(e) {})

I will get an error "Command failed: convert: no decode blah blah" with an error code (e.code) of 1.

Is there a place where I can find a list of all possible error code and their meaning?

**Comment by rwky** [comment]
Errors come from either image magick or graphicsmagick, so you'll want to check their docs.
