### ISSUE TITLE
GM gives “Stream yields empty buffer error” on Elastic Beanstalk 

### ISSUE THREAD

**Issue by ichenjia** [aheckmann/gm#464]
I am using GM for very simple thing: drawing a circle and put it in buffer. But after I check the code into Elastic Beanstalk, I am getting the "Stream yields empty buffer error" error. I am not sure why because it totally works on localhost.

Here is the code:

gm(200, 200, '#000F')
        .setFormat('png')
        .fill('black')
        .drawCircle( 50, 50, 60, 60 )
        .toBuffer(function( error, buffer )
        {
            if( error ) { res.send("error:"+error+" with content length:"+data.ContentLength);}
            res.writeHead(200, {'Content-Type': 'image/gif' });
               res.end(buffer, 'binary');
        }
Thank you very much!

**Comment by ichenjia** [comment]
It turned out to be a EC2 dependency issue.

**Comment by ArunMichaelDsouza** [comment]
@ichenjia I am getting the same error. Were you able to fix this ?

**Comment by niftylettuce** [comment]
Same error here

**Comment by kevinstubbs** [comment]
@ichenjia Is it possible for you to tell us what the EC2 dependency issue was, exactly?
