### ISSUE TITLE
5f5c774 uses hardcoded `/usr/bin/gm`

### ISSUE THREAD

**Issue by fenduru** [aheckmann/gm#465]
`gm` is not installed to `/usr/bin` on my system, and I previously had added its location to my `PATH` before using this node module.

Looks like 5f5c774 [changed to using a hardcoded `/usr/bin/gm`](https://github.com/aheckmann/gm/commit/5f5c77490aa84ed313405c88905eb4566135be31#diff-4188dbce06d21f3a05e4e5edb8aa4889R74). I think this should continue to use the shorthand `gm` and rely on the user's `PATH`

**Comment by rwky** [comment]
Whoops my fault I'll fix it shortly.
