### ISSUE TITLE
.drawText, cant get it to work

### ISSUE THREAD

**Issue by xCausxn** [aheckmann/gm#468]
Hey There,

Im trying to output drawText on my stream, however for some reason it wont draw but lines and others do work.

Also anychance you could setup gitter.im @aheckmann 

```
gm('./static/banner.jpg').font('arial', 72).stroke('#ff4dfd').fill('#ff4dfd').drawText(100, 700, 'HIHIHIHIHIHIHIHIHIHIHIHI').stream(function(err, stdout) {
    res.writeHead(200, {'Content-Type': 'image/jpeg'});
    stdout.pipe(res);
  });
```

**Comment by BoldBigflank** [comment]
I'm seeing the same thing, no text is showing up in images.

**Comment by BoldBigflank** [comment]
@xCausxn I found the issue. I had to install ghostscript like so:

`brew install ghostscript`

(I also had to `brew update` to get it to install properly)

**Comment by BoldBigflank** [comment]
You can run this in the console to see if it works

`convert -size 250x50 xc:none  -box white  -pointsize 20 -gravity center           -draw "text 0,0 \"  '  \\\"  \$  \\\\  \""           -trim +repage  text_special_dd.gif`

I was getting the following error that went away when everything started working:

    convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1153.
    convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1153.
    convert: non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3170.

**Comment by kevinbror** [comment]
What does ghostscript do for the package?
