### ISSUE TITLE
Custom parameters in .write() callback?

### ISSUE THREAD

**Issue by tnordberg** [aheckmann/gm#473]
Is there currently a way to pass in parameters to the write() callback?

```javascript
var importantVar = 'Original';

gm('in.png').write('out.png', function(err) {
          if (err) {
            throw err;
          } else {
            // How can I pass in my important var so it is 'Original' here?
            console.log(importantVar);
          }
        });

importantVar = 'Changed';
```

**Comment by Sparragus** [comment]
Wrap that with a function and pass the value you want to console.log.

```js
var importantVar = 'Original';

function processImage (logValue) {
  gm('in.png').write('out.png', function(err) {
    if (err) {
      throw err;
    } else {
      console.log(logValue);
    }
  });
}

processImage(importantVar)

importantVar = 'Changed';
```

But that will only work if you are passing a variable holding a primitive type (numbers, strings, boolean, null, undefined, Symbol). Primitive types are passed by value.

If you pass (by reference) an object or array, that one will be subject to change. In that case you will need to copy the value using something like [Object.assign()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)
