### ISSUE TITLE
Possible memory leaks on 2+ concurrent streams?

### ISSUE THREAD

**Issue by voronianski** [aheckmann/gm#489]
We're using this module in our api to convert pdf files to png:

```js
//...
gm(pdfFile)
    .density(600, 600)
    .resize(1024)
    .stream('png', (err, stdout) => {
        if (err) {
            return reject(err);
        }
        uploadOnS3(stdout, 'image/png');
    });
//...
```

Unfortunately if 2 or more files pdf are converted in the same time machine quickly gets out of space. GM adds several files to /tmp folder which grow in size rapidly to 2gb each or even more. We're using Ubuntu 14.04 though with a bit outdated GraphicsMagick (gm version: GraphicsMagick 1.3.18).

Any ideas? Thanks!

**Comment by lookfirst** [comment]
@voronianski Just curious if you found out the issue here?
