### ISSUE TITLE
Different value with identify command line.  (multiple value)

### ISSUE THREAD

**Issue by emaniacs** [aheckmann/gm#508]
I use gm (identify) to get metadata but the result is different with the original value from command line **identify** output if the value is multiple

This is the original file i've been used https://drive.google.com/file/d/0B_C8tATjmMFrVzF4blh6MExhREU/view?usp=sharing

I record process here..
https://asciinema.org/a/36mofla2lbangkkfyo1nrk94n

**Comment by aheckmann** [comment]
closed via 552a83dea
