### ISSUE TITLE
cropthumbnailimage

### ISSUE THREAD

**Issue by mikemeier** [aheckmann/gm#510]
Is something possible like http://php.net/manual/de/gmagick.cropthumbnailimage.php?

> Creates a fixed size thumbnail by first scaling the image down and cropping a specified area from the center.

At the end i've got a fixed with and height, scale is the same but the image might have been resized first (bigger/smaller) if needed.

**Comment by rodrigoalviani** [comment]
I did something like this ...
```
var gm = require('gm').subClass({imageMagick: true});
gm(stream).gravity('center').resize(width, height + '^').extent(width, height);
```

In https://github.com/rodrigoalviani/img-handler-server

**Comment by mikemeier** [comment]
Thanks @rodrigoalviani!
This works for me:
`TeamImages = new FS.Collection('teamimages', {
    stores: [new FS.Store.GridFS('teamimages', {
        transformWrite: function (fileObj, readStream, writeStream) {
            var width = 100;
            var height = 100;
            gm(readStream).gravity('center').resize(width, height + '^').extent(width, height).stream().pipe(writeStream);
        }
    })],
    filter: {
        maxSize: 500000,
        allow: {
            contentTypes: ['image/*']
        }
    }
});`
