### ISSUE TITLE
Can't save all frames from gif

### ISSUE THREAD

**Issue by Thisman** [aheckmann/gm#512]
![image](https://cloud.githubusercontent.com/assets/6540553/14077918/7c17f04e-f50a-11e5-8c60-dc09240b37cd.gif)
I try to save all frames from source gif

**index.js**

``` js
gm("./image.gif").identify(function (err, val) {
    let frames_count = val.Scene.replace(/\d* of /, "");

    for(let i = 0; i < frames_count; i++) {
        let path = `./frame${i}.png`;
        this.selectFrame(i).write(path, function () {
            console.log(arguments[3]);
        });
    }
});
```

**log**

```
gm "convert" "./image.gif[5]" "./frame5.png"
gm "convert" "./image.gif[4]" "./frame4.png"
gm "convert" "./image.gif[3]" "./frame3.png"
gm "convert" "./image.gif[2]" "./frame2.png"
gm "convert" "./image.gif[1]" "./frame1.png"
gm "convert" "./image.gif[0]" "./frame0.png"
gm "convert" "./image.gif[22]" "./frame22.png"
gm "convert" "./image.gif[21]" "./frame21.png"
// ...
```

When I open any frame , it is the first frame of gif images.

In terminal this command `"convert" "./image.gif[21]" "./frame21.png"` works fine, and saves frames that i need.

How can i save all frames from source gif?

**Comment by Slayer95** [comment]
Possibly related https://github.com/aheckmann/gm/issues/636

**Comment by slin1202** [comment]
Not sure if this will help but had to change `let frames_count = val.Scene.replace(/\d* of /, "");` to `let frames_count = val.Scene.length;`
