### ISSUE TITLE
How to generate gradient image?

### ISSUE THREAD

**Issue by liujinxing** [aheckmann/gm#518]
I know how to use graphicsmagick to create gradient image, for example:

```shell
gm convert -size 500x500 gradient:#5e99f3-#3d7ae9 gradient_transparent.png
```

but, I don't know how to use this library `gm` to create this image.

**Comment by Jabsouliman** [comment]
Have you find any solution ?

**Comment by liujinxing** [comment]
```js
import gm from 'gm';
gm(500, 500)
.in('gradient:#5e99f3-#3d7ae9')
.write('/path/to/reformat.png', err => {
  if (err) console.error(err);
  else console.log('done');
});
```

**Comment by matheushrt** [comment]
Any ideias on how to make a linear gradient from left to right?

**Comment by ajaykumar97** [comment]
@matheushrt Have you got any solution to make horizontal gradient?
