### ISSUE TITLE
Support for parenthesis?

### ISSUE THREAD

**Issue by cyberalien** [aheckmann/gm#520]
I'm trying to merge multiple images. It can be done using command line for ImageMagick:

    convert -background transparent \
        foo.png -resize '50x50!' -splice 500x0 -extent 600x500 \
        \( bar.png -resize '50x50!' -splice 500x50 -extent 600x500 \
            \( baz.png -resize '50x50!' -splice 100x100 -extent 600x500 \) -composite \
        \) -composite \
        result.png

However after adding more images to composite I'm running into command line limitations of OS. Also I'd like a uniform way to do that with ImageMagick and GraphicsMagick. 

Can it be done with GM?

**Comment by Rotemy** [comment]
Yes, you can do it like this: 

`gmFrame
     .out("\(")
     .out("-repage", `+${position.x * -1}+${position.y * -1}`)
     .out("+clone")
     .out("-alpha", "transparent")
     .font(font, fontFactor)
     .stroke(strokeColor)
     .strokeWidth(strokeWidth)
     .draw(`scale ${scale},${scale} gravity center text ${position.x + x},${position.y + y} '${text}'`)
     .stroke("none")
     .fill(fillColor || "#FFF")
     .draw(`scale ${scale},${scale} gravity center text ${position.x + x + (textAddX || 0)},${position.y + y + (textAddY || 0)} '${text}'`)
     .blur("0", blur)
     .out("\)")
     .out("-composite");`

**Comment by cyberalien** [comment]
Thanks! That code gave me ideas on how to solve problem.

However I've ran into another problem: code that works for GraphicsMagick doesn't work for ImageMagick and other way around. So in case if someone wants to use GM or IM to make sprites, here are samples:

for GM:

    var img = gm(600, 500, 'transparent');
    img.
        in('-resize', '50x50!').
        in('-page', '+500+0').
        in('foo.png');

    img.
        in('-resize', '50x50!').
        in('-page', '+500+50').
        in('bar.png');

    img.
        in('-resize', '50x50!').
        in('-page', '+100+100').
        in('baz.png');

    img.
        mosaic().
        write('result.png', err => {
            console.log('Done');
        });

and code for ImageMagick:

    var img = gm.subClass({imageMagick: true})(600, 500, 'transparent');
    img.
        out('-background', 'transparent').
        out('(').
            out('foo.png').
            out('-resize', '50x50!').
            out('-splice', '500x0').
            out('-extent', '600x500').
            out('(').
                out('bar.png').
                out('-resize', '50x50!').
                out('-splice', '500x50').
                out('-extent', '600x500').
                out('(').
                    out('baz.png').
                    out('-resize', '50x50!').
                    out('-splice', '100x100').
                    out('-extent', '600x500').
                out(')').
                out('-composite').
            out(')').
            out('-composite').
        out(')').
        out('-composite');

    img.    
        write('result.png', err => {
            console.log('Done');
        });
