### ISSUE TITLE
Compress image and set file size limit?

### ISSUE THREAD

**Issue by hidace** [aheckmann/gm#546]
It is possible to compress an image and set a file size limit (for example, if I want to compress an uploaded image, but make sure it doesn't go over 50kb)? 

Thanks.

**Comment by mnm1001** [comment]
so Is there a way to implement it?

**Comment by otanim** [comment]
@dace , @mnm1001 to decrease image size you can decrease quality, [see docs](http://aheckmann.github.io/gm/docs.html#quality) and [stackOverFlow's q&a](https://stackoverflow.com/a/26581911/5231031).
