### ISSUE TITLE
ImageMagick command called 'magick' on Windows

### ISSUE THREAD

**Issue by AtiX** [aheckmann/gm#559]
When installing a recent binary release, e.g. `ImageMagick-7.0.2-5-Q16-x64-dll.exe` from [here](http://www.imagemagick.org/script/binary-releases.php), only a `magick.exe` is installed - I assume convert got renamed because of the name conflicts with windows system tools (?)

I suggest extending gm to use either `convert` or `magick` depending on the used operating system when working with `require('gm').subClass({imageMagick: true})`.

Semi related:
https://github.com/aheckmann/gm/issues/296

**Comment by meteormatt** [comment]
For now install `ImageMagick` with "Install legacy utilities" is OK. But the ImageMagick real change the command,
![qq20160729-0 2x](https://cloud.githubusercontent.com/assets/424475/17251689/6e1b3b58-55dc-11e6-9b81-83f70b7e0854.png)

**Comment by Truedrog** [comment]
The problem exists on windows not only with convert cmd, but with others like identify etc.
Please add "magick" to cmd on windows. Thx.

**Comment by aheckmann** [comment]
Fixed by #846. Released in v1.25.0.
