### ISSUE TITLE
Support buffers in .in()

### ISSUE THREAD

**Issue by notgiorgi** [aheckmann/gm#570]
If I do:

``` javascript
var buf  = new Buffer(myBase64Img, 'base64')
var img = gm(buf)
```

Its okay, but if I want

``` javascript
var buf1  = /* ... */
var buf2  = /* ... */
var gif = gm().in(buf1).in(buf2)
```

It doesn't work.
Buffer support in `in()` would be convinient

**Comment by dcy0701** [comment]
I want this kind of effect, too

But I think'in'is the command to call the GM, and the GM command requires the file instead of the buffer

**Comment by PieceMaker** [comment]
This functionality would be great, especially when working with files in AWS S3.

**Comment by cesarpachon** [comment]
there is some workaround for this? I am  trying to merge (-flatten) some buffers and I had not discovered the proper way to do it (running in a node.js AWS lambda function with pictures retrieved from S3)
