### ISSUE TITLE
How to use -sparse-color(…), using IM as subclass of GM?

### ISSUE THREAD

**Issue by mhulse** [aheckmann/gm#583]
Not sure if I'm doing it wrong, but I can't seem to get `-sparse-color` working (here's the shell script):

```bash
$ convert background.jpg \
      -alpha set -channel A \
      -sparse-color Barycentric '%w,%[fx:h-300] opaque %w,%h transparent' \
      -background '#ffcc32' -flatten \
      background-gradiented.jpg
```

I've tried several versions of:

```bash
.sparseColor('Barycentric "%w,%[fx:h-300] opaque %w,%h transparent"')
```

… using upper/lower case, and `in()` and `out()`.

I'd love some help here! 👍 :octocat:

**Comment by mhulse** [comment]
Maybe a better question is: Is node-gm capable of hooking into IM's `-spares-color` method? If so, are there any instructions on preferred pull request workflow (like, local dev/tests)?

I'm open to doing a PR. Just don't want to waste my time if there's a limitation to implementing this method.

**Comment by tommyc38** [comment]
@mhulse I bet the reason this did not work is because you weren't using the magick command.  I couldn't figure out why none of my fx expressions were working until i did `gm('path/to/input').command('magick')..`
