### ISSUE TITLE
Error: Could not execute GraphicsMagick/ImageMagick: gm 

### ISSUE THREAD

**Issue by VicFrolov** [aheckmann/gm#599]
Hey guys, I have a docker container, where everything was working fine. Out of the blue, I am now getting the error:

` Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found`

In Dockerfile, I have 

`RUN apt-get update && apt-get install -y \
    graphicsmagick`

Not sure why this stopped working

**Comment by TitiHl** [comment]
Hi Vic,

How did you resolve this issue as I have the same problem here thanks.

Regards,

**Comment by KathiresanRamkumar95** [comment]
+1

**Comment by henock1** [comment]
+1

**Comment by ChaddPortwine** [comment]
I am having a similar issue with gm, I think.

`Warning: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%m:%T:%s" "src/css/images/banner-press.jpg" this most likely means the gm/convert binaries can't be found`

GraphicsMagick is installed, and I am able to call `gm version` from the same directory:

`GraphicsMagick 1.3.25 2016-09-05 Q16 http://www.GraphicsMagick.org/
`

If I comment out the engine: 'im' line below, the task runs and size and compression settings are applied.

`- grunt.initConfig({`
`    responsive_images: {`
`      dev: {`
`        options: {`
**`          // engine: 'im',`**
`          sizes: [{`
`            name: 'small',`
`            width: '30%',`
`            suffix: '_small',`
`            quality: 100`
`          },{`
`            name: 'large',`
`            width: '50%',`
`            suffix: '_large',`
`            quality: 100`
`          }]`
`        },`

Any help is appreciated.

**Comment by DonaldDai** [comment]
@ChaddPortwine +1, have you resolve it?

**Comment by ChaddPortwine** [comment]
@DonaldDai, Yes! Find the answer here.

[https://stackoverflow.com/questions/44029160/graphicsmagick-and-grunt-responsive-image-engine-im-breaks-task
](url)
Spoiler...user error

**Comment by DonaldDai** [comment]
@ChaddPortwine I still get the same `ERROR`, I'm on Windows and I've installed the ImageMagick which I can use it on Command Line.

**Comment by dev-fredericfox** [comment]
@[ChaddPortwine](https://github.com/ChaddPortwine) the link is dead.
