### ISSUE TITLE
Composite?

### ISSUE THREAD

**Issue by Charuru** [aheckmann/gm#6]
Can composite be added please? I need to composite one image on top of another at a specific location. I cannot figure out what to do from the source (looking at morph example). 

Please advise. Thanks!

Edit: Also, the source image needs to be cropped and resized. Should this be done with 2 steps or can this be passed as args to the composite command?

**Comment by jasan-s** [comment]
@aheckmann  I 'm using composite like so:
```
    gm(img)
          .resize(1280)
          .composite(__dirname + '/../public/images/header.jpg')
          .geometry('+0+0')
           // .crop(1280,720,0,0)
```

However I uncomment the crop line it doesnt work , any way i can apple crop? also see #675
