### ISSUE TITLE
setFormat with CMYK option

### ISSUE THREAD

**Issue by CrackerakiUA** [aheckmann/gm#616]
I am trying to make image for printing. While i am adding png to setFormat, it's working pretty well.
When i am adding CMYK format, i can't open that image and can't use it after that. Is there a special way to open CMYK images or do i have to add something like to GM?

**Comment by matthewhardern** [comment]
thought CMYK was a colourspace not a file format

```
gm('whateverfile.jpg').setFormat('png').colorspace('CMYK').write('new.png', function(err, result){

});
```

**Comment by CrackerakiUA** [comment]
Sorry for late response, this works super great.
