### ISSUE TITLE
Is there any way to set the character spacing or line spacing?

### ISSUE THREAD

**Issue by hellovigoss** [aheckmann/gm#686]
I got these options for my characters in my graph, and I use not only English but Chinese like this
```javascript
gm(picPath)
    .noProfile()
    .fill("rgb(12,202,255)")
    .font(font[0])
    .fontSize(172)
    .drawText(0, -323, '真棒', 'Center')
```
I want to control the space of characters "真棒", what option should I choose?

**Comment by reggi** [comment]
I just posted the same thing! https://github.com/aheckmann/gm/issues/822 
Did you ever find a solution?

**Comment by reggi** [comment]
I found a way! `.in('-kerning', '19')`

**Comment by hellovigoss** [comment]
thanks
