### ISSUE TITLE
when i use Chinese code in gm.drawText,  garbled characters appeared.

### ISSUE THREAD

**Issue by EliazTray** [aheckmann/gm#694]
![image](https://user-images.githubusercontent.com/16015431/33335671-a2ed46cc-d4a8-11e7-9684-780058ce5a85.png)
then in test.png
![image](https://user-images.githubusercontent.com/16015431/33335771-f2cc7956-d4a8-11e7-9008-467aa73cdf4a.png)

is there a way to solve it? i used 'yahei'.ttf

**Comment by OneMoreMile** [comment]
anyupdate on this issue?  i encountered the same

**Comment by EliazTray** [comment]
@OneMoreMile The server environment is Linux, so ok.but in windows, it is bad

**Comment by yitian-yan** [comment]
check the encoding of windows，support Unicode ?

**Comment by EliazTray** [comment]
> check the encoding of windows，support Unicode ?

yep, until now, need the server enviroment install related fonts.
