### ISSUE TITLE
this most likely means the gm/convert binaries can't be found

### ISSUE THREAD

**Issue by xuya227939** [aheckmann/gm#731]
I installed the corresponding NPM package according to the tutorials, but I always reported this mistake, Google did not find a solution.  Please help me to solve it. Thank you.

**Comment by xuya227939** [comment]
I'm solve it,  Do not use npm install！！！

**Comment by Yalhu** [comment]
What should install ??  @xuya227939

**Comment by xuya227939** [comment]
@Yalhu What?

**Comment by louis71barker** [comment]
Sorry, what do you mean dont use npm install, what did you do instead to get this working

**Comment by xuya227939** [comment]
I'm sorry. It's been a long time, I forgot.

@louis71barker  @Yalhu

**Comment by V00doo1** [comment]
Tried installing it with yarn which resolves with "gm does has no binaries".

I solved it by installing it using the Ubuntu apt-get package manager. had it installed in a docker container where I was running my server.

The solution might be to install the package locally with your package manager for the OS

> Sorry, what do you mean dont use npm install, what did you do instead to get this working
