### ISSUE TITLE
Is it possible to flatten a pdf (and all its pages) without writing to image files?

### ISSUE THREAD

**Issue by changavila** [aheckmann/gm#736]
So i have a AWS lambda that gets the PDF buffer of the file from s3, and flattens the pdf to images, and write it back to the pdf the uploads it to S3. But with this, i can only process one page at a time. Is it possible to process all the pages at once then retrieve the all pages flattened in one PDF buffer?

This is my sample code snippet:
```javascript
gm(material, 'material1.pdf')
    .density(216,154)
    .define('pdf:use-cropbox=true')
    .flatten()
    .toBuffer('PDF',function (err, buffer) {
        if (err) return handle(err);
        console.log('done!');

        s3Helper.upload(buffer, options);
    });
```

**Comment by demsey2** [comment]
hi @changavila 
I have the same requirement, did you find any solution?

**Comment by changavila** [comment]
Hi @demsey2, 
This is possible by using `toBuffer('PDF' , function(err,buffer)`. You will have to use imagemagick here rather than using the graphicsmagick. To do this you must initialize graphicsmagick to:
`const gm = require('gm').subClass({ imageMagick: true });`

**Comment by demsey2** [comment]
thanks a lot

**Comment by puneeth8994** [comment]
@changavila Off topic but can you help me understand how you got gm to work on lambda? I have added the binaries and pointed the appPath to it but I get the error message that "binaries can't be found"

**Comment by changavila** [comment]
I think you don't need to add the binaries, since the AWS lambda has already imageMagick in it.

**Comment by ronaksavla** [comment]
@puneeth8994  I am getting Error: spawn EACCES
@changavila  seems like the new update has removed convert modules. I confirmed with tech support
https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/

I followed these steps to get Static Binaries for Lambda:
https://gist.github.com/bensie/56f51bc33d4a55e2fc9a
ImageMagic version use: 6.9.10-5

Code:
`var IM_PATH = "var/task/imagemagick/bin/";
process.env['LD_LIBRARY_PATH'] = 'var/task/imagemagick/lib/';
process.env['PATH'] = process.env['PATH'] + ':' + IM_PATH + ':' + process.env['LD_LIBRARY_PATH'];

var gm = require('gm').subClass({
    imageMagick: true,
    appPath: 'var/task/imagemagick/bin/',
  });

  gm('image.png')
    .resize(240, 240, '!')
    .write('/tmp/resize.png', function (err) {
      if (!err) console.log('done');
      else {
        console.log(err);
      }
    });
`
Folder structure for Node js 8.10 lambda: 
![image](https://user-images.githubusercontent.com/7759130/61564072-6f0d4600-aa2a-11e9-8ab0-cbbd33b0c611.png)

gm version: "1.23.1"

```
{ Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at spawn (/var/task/node_modules/cross-spawn/index.js:17:18)
    at gm._spawn (/var/task/node_modules/gm/lib/command.js:224:14)
    at /var/task/node_modules/gm/lib/command.js:101:12
    at series (/var/task/node_modules/array-series/index.js:11:36)
    at gm._preprocess (/var/task/node_modules/gm/lib/command.js:177:5)
    at gm.write (/var/task/node_modules/gm/lib/command.js:99:10)
    at exports.handler (/var/task/index.js:22:6) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
```
