### ISSUE TITLE
Permission denied for gm binaries installed within AWS Lambda

### ISSUE THREAD

**Issue by basimhennawi** [aheckmann/gm#762]
I'm using GraphicsMagick in my Lambda function (NodeJs 8.10) , for that I need to install both:

- the NodeJs library for it [gm][1] (latest 1.23.1) [That's fine!]
- and the GM binaries

To get the gm binaries on the Lambda, after some googling/stackingoverflow, get to create this [github gist][2] that states what I did briefly as follow:

- Create EC2 instance with Amazon Linux AMI that matches AWS Lambda's runtime.
- Install the gm there, tar it, copy it to my lambda, zipped it, packaged it, and deployed it.

Now the problem is that I got "Stream yields empty buffer" error whenever I used and manipulating method from gm, for that needed to check if my installed binaries there is correct, so added the following in my lambda handler function:

    const exec = require('child_process').exec;
    exec("gm -help", console.log)

And got the following "Permission denied" error as shown below:

[![enter image description here][3]][3]

Any clue? Thanks in advance!

  [1]: https://github.com/aheckmann/gm
  [2]: https://gist.github.com/basimhennawi/21c39f9758b0b1cb5e0bd5ee08b5be58#file-graphicsmagick-txt
  [3]: https://i.stack.imgur.com/hOjFU.png

**Comment by basimhennawi** [comment]
Got it solved! Too much details to list here. Gonna close it.

**Comment by KempfCreative** [comment]
@basimhennawi can you elaborate somewhere else? I too have this use case and issue :)

**Comment by puneeth8994** [comment]
@basimhennawi Facing the same issue, what was your final folder structure? and can you elaborate a bit on the issue?
