### ISSUE TITLE
gm("img.png").shadow(radius, sigma) sigma is mean what?

### ISSUE THREAD

**Issue by Chaunjie** [aheckmann/gm#766]
gm("img.png").shadow(radius, sigma) sigma is mean what, how do I use it?

**Comment by skeddles** [comment]
trying to figure this out too, i dont really understand the difference. But either way the shadow is always white and replaces the original image so I don't see how this function is useful.

**Comment by skeddles** [comment]
trying to figure this out too, i dont really understand the difference. But either way the shadow is always white and replaces the original image so I don't see how this function is useful.

**Comment by vinaymuthanna0727** [comment]
@Chaunjie 
Are you able to implement the shadow in using gm ?
