### ISSUE TITLE
Can't convert raw image types

### ISSUE THREAD

**Issue by justin-dx** [aheckmann/gm#802]
I’m trying to convert a small selection of different raw file types (cr2, nef, orf, arw, dng) into tiffs.
When I use GraphicsMagick from the cli I get the expected results based on the settings in my delegates file.

Running `gm convert image.nef out.nef.tiff` gives me a tiff that is 35Mb and 4284x2844.
When I run the same command via gm, I get a tiff that is 205Kb and 320x212.
```
relevant code...
const rawFilePath = 'image.nef';
var fileBuffer = fs.readFileSync(rawFilePath);

async function gmConvert(buffer, filename) {
  return new Promise((resolve, reject) => {
    gm(buffer, filename)
	  .command("convert")
	  .toBuffer("tiff", (err, data) => {
		if (!err) {
		  resolve(data);
		} else {
		  reject(err);
		}
	  });		
  });
}
	
var wstream = fs.createWriteStream('out.nef.tiff');
wstream.write(outData);
wstream.end();	
```

The only raw image that generates a full sized tiff is cr2. 

File Type | Result
------------ | -------------
CR2 | Works
NEF | Very small output image
ORF | Stream yields empty buffer
ARW | Stream yields empty buffer
DNG | Very small output image

What am I doing wrong?

GraphicsMagick version: GraphicsMagick 1.3.35 2020-02-23 Q8
gm version: 1.23.1
node version: 12.16.1

[baby.nef](https://s3.amazonaws.com/Sample_NEFs/baby.nef.zip)

**Comment by justin-dx** [comment]
When using raw images, they are decoded with dcraw. dcraw doesn't accept streams/buffers as input - only filepaths. Now I write the buffer to a file and reference that in gm() commands.

CR2s worked because they are share a signature with tiffs and are are similar enough that GraphicsMagick can just decode them. Small thumbnails were caused by the same issue - they were treated as tiffs.

**Comment by backsapce** [comment]
sony arw file. it's work 
```sh
brew install dcraw
```
```js
var gm = require('gm').subClass({imageMagick: false});


 gm('xxx.ARW')
	  .command("convert")
	  .write("xxx.png", (err, data) => {
		  console.log(err,data)
	  });
```
